export const GET_ALL_QUESTION = 'GET_ALL_QUESTION';
export const SUBMIT_ALL_ANSWER = 'SUBMIT_ALL_ANSWER';
export const GET_ALL_QUESTION_FAILS = 'GET_ALL_QUESTION_FAILS';
export const GET_ALL_QUESTION_SUCCESS = 'GET_ALL_QUESTION_SUCCESS';
export const SUBMIT_ALL_ANSWER_SUCCESS = 'SUBMIT_ALL_ANSWER_SUCCESS';
export const SUBMIT_ALL_ANSWER_FAILS = 'SUBMIT_ALL_ANSWER_FAILS';